name: OSSF Scorecard

on:
  workflow_dispatch

jobs:
  release:
    name: Run Scorecard
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
  
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: OSSF Scorecard action
        uses: ossf/scorecard-action@v2.3.1
        with:
          results_file: 'scorecard_results.json'
          results_format: 'json'
